language: node_js
node_js: "12"
branches:
  only:
    - working
    - main
cache:
  directories:
    - node_modules
services:
  - mongoose
test: 
  adapter: mongoose
env:
  TEST_DB: "travis_test_dono_db"
